---
name: OpenCourier app beta for Android CI

on:
  push:
    tags:
      - 'v*'  # Runs only for version tags like v1.0.0
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Android Release
        run: |
          set -x
          nix develop --impure --command -- make apk-release BUILD_NUMBER=${{ github.run_number }}

      - uses: parasitid/sign-android-release@v5
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_JKS }}
          # The alias for the keystore, stored as a secret
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
      - name: Rename APK
        run: |
          set -x
          PROJECT_NAME=$(node -p "require('./package.json').name")
          cp ${{steps.sign_app.outputs.signedReleaseFile}} \
            ${PROJECT_NAME}_${{ github.ref_name }}+${{ github.run_number }}.apk

          cp ${{steps.sign_app.outputs.signedReleaseFile}} \
            ${PROJECT_NAME}_latest.apk
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.apk"
        env:
